from __future__ import annotations

from collections.abc import AsyncIterator, Sequence
from typing import Any, Protocol

from trading.contracts import (
    BrokerHealth,
    BrokerOrder,
    Instrument,
    MarginSnapshot,
    MarketEvent,
    OrderAck,
    OrderUpdate,
    PositionSnapshot,
    TradeFill,
    ValidatedOrder,
)


class BrokerAdapter(Protocol):
    async def authenticate(self) -> None: ...
    async def connect(self) -> None: ...
    async def disconnect(self) -> None: ...
    async def health(self) -> BrokerHealth: ...
    async def load_instruments(self) -> Sequence[Instrument]: ...
    async def subscribe_market_data(self, instruments: Sequence[Instrument], mode: str = "full") -> None: ...
    async def unsubscribe_market_data(self, instruments: Sequence[Instrument], mode: str = "full") -> None: ...
    def stream_market_data(self) -> AsyncIterator[MarketEvent]: ...
    def stream_order_updates(self) -> AsyncIterator[OrderUpdate]: ...
    async def place_order(self, order: ValidatedOrder) -> OrderAck: ...
    async def modify_order(self, broker_order_id: str, **changes: Any) -> OrderAck: ...
    async def cancel_order(self, broker_order_id: str) -> OrderAck: ...
    async def cancel_all(self) -> Sequence[OrderAck]: ...
    async def get_order(self, broker_order_id: str) -> BrokerOrder: ...
    async def get_orders(self) -> Sequence[BrokerOrder]: ...
    async def get_trades(self) -> Sequence[TradeFill]: ...
    async def get_positions(self) -> Sequence[PositionSnapshot]: ...
    async def get_holdings(self) -> Sequence[PositionSnapshot]: ...
    async def get_funds(self) -> MarginSnapshot: ...
    async def calculate_margin(self, orders: Sequence[ValidatedOrder]) -> MarginSnapshot: ...
    async def reconcile(self) -> dict[str, Any]: ...
